const button_div = document.getElementById('button');
const quote_section = document.getElementById('section');
const quotes = [
  'The fortune you seek is in another cookie.',
  'A closed mouth gathers no feet.',
  'A conclusion is simply the place where you got tired of thinking.',
  'A cynic is only a frustrated optimist.',
  'A foolish man listens to his heart. A wise man listens to cookies.',
  'You will die alone and poorly dressed.',
  "A fanatic is one who can't change his mind, and won't change the subject.",
  "If you look back, you'll soon be going that way.",
  'You will live long enough to open many fortune cookies.',
  'An alien of some sort will be appearing to you shortly.',
  'Do not mistake temptation for opportunity.',
  'Flattery will go far tonight.',
  'He who laughs at himself never runs out of things to laugh at.',
  'He who laughs last is laughing at you.',
  'He who throws dirt is losing ground.',
  'Some men dream of fortunes, others dream of cookies.',
  'The greatest danger could be your stupidity.',
  "We don't know the future, but here's a cookie.",
  "The world may be your oyster, but it doesn't mean you'll get its pearl.",
  'You will be hungry again in one hour.',
  'The road to riches is paved with homework.',
  'You can always find happiness at work on Friday.',
  'Actions speak louder than fortune cookies.',
  'Because of your melodic nature, the moonlight never misses an appointment.',
  "Don't behave with cold manners.",
  "Don't forget you are always on our minds.",
  'Fortune not found? Abort, Retry, Ignore.',
  'Help! I am being held prisoner in a fortune cookie factory.',
  "It's about time I got out of that cookie.",
  'Never forget a friend. Especially if he owes you.',
  'Never wear your best pants when you go to fight for freedom.',
  'Only listen to the fortune cookie; disregard all other fortune telling units.',
  'It is a good day to have a good day.',
  'All fortunes are wrong except this one.',
  'Someone will invite you to a Karaoke party.',
  "That wasn't chicken.",
  'There is no mistake so great as that of being always right.',
  'You love Chinese food.',
  'I am worth a fortune.',
  'No snowflake feels responsible in an avalanche.',
  'You will receive a fortune cookie.',
  'Some fortune cookies contain no fortune.',
  "Don't let statistics do a number on you.",
  'You are not illiterate.',
  'May you someday be carbon neutral.',
  'You have rice in your teeth.',
  'Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37',
  'Ask your mom instead of a cookie.',
  'This cookie contains 117 calories.',
  'Hard work pays off in the future. Laziness pays off now.',
  "You think it's a secret, but they know.",
  "If a turtle doesn't have a shell, is it naked or homeless?",
  'Change is inevitable, except for vending machines.',
  "Don't eat the paper.",
  'There will come a time when you wish you’d given love a chance.',
  'We cannot do great things; only small things with great love.',
  'Don’t let heartbreak slow down your quest to find love.',
  'A secret admirer is now plotting how to win your heart.',
  'Love is the triumph of imagination over intelligence.',
  'Love is the only medicine for a broken heart.',
  'Only love makes us see ordinary things in an extraordinary way.',
  'Count your blessings by thinking of those who love you.',
  'The greatest gift of all, is love.',
  'Hug your loved ones today.',
  'To love, is to forgive.',
  'Love conquers all.',
  'Friendship is the first step towards love.',
  'Excitement and intrigue follow you closely wherever you go.',
  'Don’t be afraid to take the plunge.',
  'Being a spendthrift is not healthy. Practice the act of giving and sharing.',
  'Hope is what keeps us alive.',
  'The dream is within you.',
  'Trust those who return your acts of kindness. Respond with kinder gestures.',
  'Never lose the ability to find beauty in ordinary things.',
  'No one can make you feel inferior without your consent.',
  'Nature, love, and patience are the three best physicians.',
  'Your many hidden talents will become obvious to those around you.',
  'Learn to trust in the Lord, for He is your weapon against evil.',
  'Learn to take responsibility for your actions.',
  'In the end, there are three things that last: faith, hope and love.',
  'Do not waste time hating your enemies, pray for them instead.',
  'Tomorrow will be a better day. And if not, there’s always chocolate.'
];

function newQuote() {
  const randomNumber = Math.floor(Math.random() * quotes.length);
  quote_section.innerHTML = quotes[randomNumber];
}

function main() {
  button_div.addEventListener('click', () => newQuote());
}

main();
